export const mockComics = [
  {
    id: "comic-1",
    title: "(Tập lẻ) Fullmetal Alchemist - Cang giả kim thuật sư",
    slug: "fullmetal-alchemist",
    productId: "89100303",
    sku: "6242213410001",
    isbn: "978-604-2-24361-2",
    price: 67500,
    originalPrice: 75000,
    currency: "VND",
    authors: ["Hiromu Arakawa"],
    targetAudience: "Tuổi mới lớn (15 – 18)",
    dimensions: "13x18 cm",
    pages: 278,
    format: "bìa mềm",
    weight: "310 gram",
    editionType: "ban_in_dau",
    series: "Fullmetal Alchemist - Cang giả kim thuật sư",
    description: "Bộ truyện manga huyền thoại của Hiromu Arakawa.",
    coverImage: "https://bizweb.dktcdn.net/100/576/749/products/f4b78197-8839-461d-8950-2d9529dbaf48.jpg",
    productType: "Manga - comic",
    url: "https://nxbkimdong.com.vn/tap-le-fullmetal-alchemist-cang-gia-kim-thuat-su",
    publisher: { id: "pub-1", name: "Nhà xuất bản Kim Đồng", slug: "nxb-kim-dong" },
    volumes: [
      {
        id: "vol-1",
        comicId: "comic-1",
        title: "Tập 01",
        slug: "fullmetal-alchemist-tap-01",
        productId: "89100303-1",
        sku: "6242213410001",
        barcode: "6242213410001",
        price: 67500,
        originalPrice: 75000,
        volumeNumber: 1,
        volumeLabel: "Tập 01",
        pages: 278,
        format: "bìa mềm",
        dimensions: "13x18 cm",
        weight: "310 gram",
        coverImage: "https://bizweb.dktcdn.net/100/576/749/products/f4b78197-8839-461d-8950-2d9529dbaf48.jpg",
        url: "https://nxbkimdong.com.vn/tap-le-fullmetal-alchemist-cang-gia-kim-thuat-su",
        available: false,
        inventoryQty: 0,
        gifts: [
          { id: "gift-1", name: "Standee", description: null, imageUrl: null, isFes: false, giftType: "combo", rarity: "normal", createdAt: new Date(), updatedAt: new Date(), volumeId: null, eventId: null }
        ],
      },
      {
        id: "vol-2",
        comicId: "comic-1",
        title: "Tập 02",
        slug: "fullmetal-alchemist-tap-02",
        productId: "89100303-2",
        sku: "6242213410002",
        barcode: "6242213410002",
        price: 67500,
        originalPrice: 75000,
        volumeNumber: 2,
        volumeLabel: "Tập 02",
        pages: 278,
        format: "bìa mềm",
        dimensions: "13x18 cm",
        weight: "310 gram",
        coverImage: "https://bizweb.dktcdn.net/100/576/749/products/1c12b69f-c446-41d1-9635-e1a30e2abaed.jpg",
        url: "https://nxbkimdong.com.vn/tap-le-fullmetal-alchemist-cang-gia-kim-thuat-su",
        available: true,
        inventoryQty: 9,
        gifts: [],
      },
    ],
    eventGifts: [],
  },
  {
    id: "comic-2",
    title: "Thám tử lừng danh Conan - Tập 100",
    slug: "conan-tap-100",
    productId: "conan-100",
    sku: "conan-100",
    isbn: "978-604-2-12345-6",
    price: 35000,
    originalPrice: 40000,
    currency: "VND",
    authors: ["Gosho Aoyama"],
    targetAudience: "Tuổi mới lớn (15 – 18)",
    dimensions: "11.5x17.6 cm",
    pages: 192,
    format: "bìa mềm",
    weight: "180 gram",
    editionType: "ban_in_dau",
    series: "Thám tử lừng danh Conan",
    description: "Conan tiếp tục hành trình giải án.",
    coverImage: "https://bizweb.dktcdn.net/100/576/749/products/conan100.jpg",
    productType: "Manga - comic",
    url: "https://nxbkimdong.com.vn/tham-tu-lung-danh-conan-tap-100",
    publisher: { id: "pub-1", name: "Nhà xuất bản Kim Đồng", slug: "nxb-kim-dong" },
    volumes: [
      {
        id: "vol-3",
        comicId: "comic-2",
        title: "Tập 100",
        slug: "conan-tap-100",
        productId: "conan-100",
        sku: "conan-100",
        barcode: "conan-100",
        price: 35000,
        originalPrice: 40000,
        volumeNumber: 100,
        volumeLabel: "Tập 100",
        pages: 192,
        format: "bìa mềm",
        dimensions: "11.5x17.6 cm",
        weight: "180 gram",
        coverImage: "https://bizweb.dktcdn.net/100/576/749/products/conan100.jpg",
        url: "https://nxbkimdong.com.vn/tham-tu-lung-danh-conan-tap-100",
        available: true,
        inventoryQty: 50,
        gifts: [],
      }
    ],
    eventGifts: [],
  },
] as any[];

export const mockEvents = [
  {
    id: "event-1",
    publisherId: "pub-1",
    name: "Kim Đồng FES 2025",
    eventType: "fes",
    startDate: "2025-08-20T10:00:00",
    endDate: "2025-08-25T18:00:00",
    description: "Sự kiện hội sách lớn nhất năm với nhiều quà tặng hấp dẫn.",
    eventGifts: [
      {
        id: "event-gift-1",
        eventId: "event-1",
        volumeId: null,
        giftId: "gift-2",
        giftName: "Bộ bookmark Kim Đồng FES 2025",
        condition: "Mua combo bất kỳ trong sự kiện",
        imageUrl: null,
        gift: { id: "gift-2", name: "Bookmark FES 2025", description: null, imageUrl: null, isFes: true, giftType: "fes", rarity: "limited", createdAt: new Date(), updatedAt: new Date(), volumeId: null, eventId: null }
      }
    ]
  }
] as any[];

export const mockStandaloneGifts = [
  {
    id: "gift-2",
    name: "Bookmark FES 2025",
    description: null,
    imageUrl: null,
    volumeId: null,
    eventId: "event-1",
    isFes: true,
    giftType: "fes",
    rarity: "limited",
    createdAt: new Date(),
    updatedAt: new Date(),
  }
] as any[];
